# Generated by Django 5.0 on 2023-12-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('EMAIL', 'EMAIL'), ('LINKEDIN', 'LINKEDIN'), ('GITHUB', 'GITHUB'), ('TWITTER', 'TWITTER'), ('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('WEBSITE', 'WEBSITE'), ('OTHER', 'OTHER')], default=1, max_length=50, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
