# Generated by Django 5.0 on 2023-12-24 18:05

import django.db.models.deletion
import resume.enum
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('EMAIL', 'EMAIL'), ('LINKEDIN', 'LINKEDIN'), ('GITHUB', 'GITHUB'), ('TWITTER', 'TWITTER'), ('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('WEBSITE', 'WEBSITE'), ('OTHER', 'OTHER')], default=resume.enum.ContactTypes['EMAIL'], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL), max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
