# Generated by Django 5.0 on 2023-12-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_contact_type_alter_resume_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='currently',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='currently',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
